### ISSUE TITLE
Crashes when searching by Notes (MAC)

### ISSUE THREAD

**Issue by iocarala** [apolcaro/article-manager#2]
### Terminal output:
Traceback (most recent call last):
  File "articleManager.py", line 108, in passSearch
    self.mainWindow.searchFiles(str(self.combobox_field.currentText()), self.textbox_value.text())
  File "articleManager.py", line 265, in searchFiles
    matches = self.folderTree.findFilesBy(field, value)
FoldOrg.py", line 231, in findFilesBy
    matches = self._findFilesBy_traversal(self.tree, field, value, list())
FoldOrg.py", line 241, in _findFilesBy_traversal
    self._findFilesBy_traversal(subfolder, field, value, matches)   
FoldOrg.py", line 241, in _findFilesBy_traversal
    self._findFilesBy_traversal(subfolder, field, value, matches)   
FoldOrg.py", line 238, in _findFilesBy_traversal
    if self._findFilesBy_checkMatch(file, field, value):
FoldOrg.py", line 248, in _findFilesBy_checkMatch
    return file.data[field].find(value) != -1  #Assumes fields are always strings!
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by iocarala** [comment]
It works now.
